default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= Rails.application.credentials.database[:name] %>
  username: <%= Rails.application.credentials.database[:user] %>
  password: <%= Rails.application.credentials.database[:password] %>
  port: <%= Rails.application.credentials.database[:port] || "5432" %>
  host: <%= Rails.application.credentials.database[:host] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: jdc_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
